### ISSUE TITLE
Need build suitesparse_wrapper shim

### ISSUE THREAD

**Issue by andreasnoack** [ViralBShah/SuiteSparseBuilder#4]
Currently located [here](https://github.com/JuliaLang/julia/blob/2c5aec90c9f9b58158eb61a516f6c2565c25eb9a/deps/SuiteSparse_wrapper.c) and the makefile targets are [here](https://github.com/JuliaLang/julia/blob/2c5aec90c9f9b58158eb61a516f6c2565c25eb9a/deps/suitesparse.mk). What would be easier/best way to build `libsuitesparse_wrapper` as part of `SuiteSparseBuilder`?

cc: @staticfloat

**Comment by staticfloat** [comment]
I would copy that `.c` file to this repository, put it into `<repository_root>/local_srcs/suitesparse_wrapper/SuiteSparse_wrapper.c`, then in your `sources` list, add `"./local_srcs"`.  It will be brought into the workspace and you can adapt the Makefile lines to compile it against OpenBLAS in `$prefix/lib`, and install it alongside in `$prefix/lib` so that Julia can open up the wrapper lib when this package gets installed.

**Comment by andreasnoack** [comment]
I got this mostly working but I think the `rpath` stuff is not right. This is how it looks like right now.

```
andreasnoack@anubis:/data/andreasnoack/SuiteSparseBuilder/products/lib$ ldd libsuitesparse_wrapper.so
        linux-vdso.so.1 =>  (0x00007ffc05fe8000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libcholmod.so.3 (0x00007fbb24ea2000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libumfpack.so.5 (0x00007fbb24bca000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libspqr.so.2 (0x00007fbb24988000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbb245a8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbb24252000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbb2404a000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libamd.so.2 (0x00007fbb23e3d000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libcolamd.so.2 (0x00007fbb23c34000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libsuitesparseconfig.so.5 (0x00007fbb$
3a31000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libccolamd.so.2 (0x00007fbb23824000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libcamd.so.2 (0x00007fbb23616000)
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libopenblas64_.so.0 => not found
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libopenblas64_.so.0 => not found
        /data/andreasnoack/SuiteSparseBuilder/products/lib/./libopenblas64_.so.0 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbb23290000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbb23079000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbb253a9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbb22e5a000)
```

I've tried both with the `RPATH` enable and disabled in https://github.com/JuliaLinearAlgebra/SuiteSparseBuilder/blob/master/src/SuiteSparse_wrapper/Makefile. Which was inspired by one of the Makefiles from `BinaryBuilder.jl`. Do you see what is wrong?

See also the build log https://api.travis-ci.org/v3/job/388677491/log.txt

**Comment by andreasnoack** [comment]
Fixed by latest changes to BinaryBuilder
